//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserCodeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParserCodeGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주석과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클래스 생성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateClass {
            get {
                return ResourceManager.GetString("CreateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Class 생성 옵션과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateClassOption {
            get {
                return ResourceManager.GetString("CreateClassOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 생성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static byte[] example {
            get {
                object obj = ResourceManager.GetObject("example", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문법과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Grammar {
            get {
                return ResourceManager.GetString("Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문법 정의과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Grammar_Def {
            get {
                return ResourceManager.GetString("Grammar_Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인덱스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Namespace 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InputNamespaceHint {
            get {
                return ResourceManager.GetString("InputNamespaceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 옵션과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LanguageOption {
            get {
                return ResourceManager.GetString("LanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   길이과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예제 불러오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadExample {
            get {
                return ResourceManager.GetString("LoadExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Namespace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   순서과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바로 보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string QuickView {
            get {
                return ResourceManager.GetString("QuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정규 표현식과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   결과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   테스트 문자열과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Test_String {
            get {
                return ResourceManager.GetString("Test_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   빌드 테스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TestBuild {
            get {
                return ResourceManager.GetString("TestBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   값과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
